global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: backend
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']

  - job_name: node
    static_configs:
      - targets: ['node_exporter:9100']
