global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'airflow'
    metrics_path: '/metrics'
    static_configs:
      - targets: ["statsd-exporter:9102"]

  - job_name: 'airflow-worker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['airflow-worker:8080']  # worker exposes 8080/metrics too
      
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

