{
 "title": "Fraud Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[5m])) * 100",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Installed" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "Swapped"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total[5m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Disk Storage ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(device) (node_filesystem_avail_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Disc Space",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(device) ((node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Read Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Predict API Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(client)(rate(model_predict_total[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(client)(rate(model_predict_success_total[5m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum by(client)(rate(model_predict_failure_total[5m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Explain API Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(client)(rate(model_explain_total[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(client)(rate(model_explain_success_total[5m]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum by(client)(rate(model_explain_failure_total[5m]))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "API Usage Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_predict_total/(model_explain_total+model_predict_total)",
     "legendFormat": "predict"
    },
    {
     "expr": "model_explain_total/(model_predict_total+model_explain_total)",
     "legendFormat": "explain"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(model_predict_true_positive_total+model_predict_true_negative_total)/(model_predict_true_positive_total+model_predict_true_negative_total+model_predict_false_positive_total+model_predict_false_negative_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precision",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  model_predict_true_positive_total\n) / (\n  model_predict_true_positive_total\n  + model_predict_false_positive_total\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "F1-Score",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  2 * model_predict_true_positive_total\n) / (\n  2 * model_predict_true_positive_total\n  + model_predict_false_positive_total\n  + model_predict_false_negative_total\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}